openapi: 3.0.1
info:
  title: HSBC RAG Chatbot API
  version: 1.0.0
paths:
  /api/query:
    post:
      summary: Query the indexed HSBC documents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                top_k:
                  type: integer
              required:
                - question
      responses:
        "200":
          description: Answer plus citations
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  retrieved:
                    type: array
                    items:
                      type: object
                      properties:
                        source:
                          type: string
                        page:
                          type: integer
                        text:
                          type: string
  /api/ingest:
    post:
      summary: Upload and ingest PDF
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: Ingest result
